---
- hosts: all
  sudo: true
  tasks:
    - name: Mise à jour de l'apt cache
      apt: update_cache=yes
    - name: Installation d'Apache2
      apt: name=apache2 state=present
    - name: Installation de Git
      apt: name=git state=present
    - name: Installation de Maven
      apt: name=maven state=present