---
- hosts: all
  vars:
    sonar:
      base_dir: "/usr/local/sonar"
      owner: "sonar"
      group: "sonar"
      name: "sonarqube-5.1"
      archive: "sonarqube-5.1.zip"
      jdbc: "sonar"
    artifactory:
      owner: "artifactory"
      group: "artifactory"
      name: "artifactory"
      base_dir: "/opt/artifactory"
      version: "4.6.0"
    java_home: "/usr/lib/jvm/java-8-openjdk-amd64/jre"

  sudo: true
  tasks:
    - name: Mise à jour de l'apt cache
      apt: update_cache=yes
    - include: playbooks/install.yml
    - include: playbooks/jenkins.yml
    - include: playbooks/mysql.yml
    - include: playbooks/sonar.yml
    - include: playbooks/tomcat.yml
    - include: playbooks/artifactory.yml