---
- name: Ajout de la clef APT Jenkins 
  apt_key: url=https://jenkins-ci.org/debian/jenkins-ci.org.key
- name: Ajout du dépôt Jenkins dans les sources
  shell: "echo deb http://pkg.jenkins-ci.org/debian binary/ > /etc/apt/sources.list.d/jenkins.list"
- name: Mise à jour de l'apt cache
  apt: update_cache=yes
- name: Installation de Jenkins
  apt: name=jenkins update_cache=yes
- name: Démarrage de Jenkins
  service: name=jenkins state=started enabled=yes
- name: En attente de Jenkins...
  command: curl --head --silent http://localhost:8080/jnlpJars/jenkins-cli.jar/
  register: result
  until: result.stdout.find("200 OK") != -1
  retries: 12
  delay: 5
  changed_when: false
- name: Installation des plugins pour Jenkins
  shell: "wget http://localhost:8080/jnlpJars/jenkins-cli.jar && \
          java -jar jenkins-cli.jar -s http://localhost:8080 install-plugin git"
- name: Création du job Jenkins
  shell: "echo '{{ lookup('file', '../jenkins_config/usine_logicielle_job.xml') }}' | java -jar jenkins-cli.jar -s http://localhost:8080 create-job UsineLogicielle && \
         rm -rf jenkins-cli.jar"
- name: Redémarrage de Jenkins
  service: name=jenkins state=restarted
