---
- name: Installation de Postfix
  apt: name=postfix state=present
- name: Installation dependance de Postfix - mailutils
  apt: name=mailutils state=present
- name: Installation dependance de Postfix - libsasl2-2
  apt: name=libsasl2-2 state=present
- name: Installation dependance de Postfix - ca-certificates
  apt: name=ca-certificates state=present
- name: Installation dependance de Postfix - libsasl2-modules
  apt: name=libsasl2-modules state=present
  
- name: Transfert de certificat Thawte Premium Server CA
  copy: src=fichiers/mail/Thawte_Premium_Server_CA.pem dest=/etc/ssl/certs/Thawte_Premium_Server_CA.pem
- name: Transfert de fichier de configuration Postfix pour relai vers gmail
  copy: src=fichiers/mail/main.cf dest=/etc/postfix/main.cf
- name: Transfert de fichier de configuration Postfix pour envoie des donnees de compte
  copy: src=fichiers/mail/sasl_passwd dest=/etc/postfix/sasl/sasl_passwd
  
- name: Commandes shell de configuration Postfix
  shell: " cat /etc/ssl/certs/Thawte_Premium_Server_CA.pem | sudo tee -a /etc/postfix/cacert.pem && \
           chmod 400 /etc/postfix/sasl/sasl_passwd && \
           postmap /etc/postfix/sasl/sasl_passwd && \
           chown postfix /etc/postfix/sasl/sasl_passwd
          "
          
- name: Relancer Postfix
  service: name=postfix state=restarted